/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TvShowService } from "../tvShow.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TvShowCreateInput } from "./TvShowCreateInput";
import { TvShow } from "./TvShow";
import { TvShowFindManyArgs } from "./TvShowFindManyArgs";
import { TvShowWhereUniqueInput } from "./TvShowWhereUniqueInput";
import { TvShowUpdateInput } from "./TvShowUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TvShowControllerBase {
  constructor(
    protected readonly service: TvShowService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TvShow })
  @nestAccessControl.UseRoles({
    resource: "TvShow",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTvShow(@common.Body() data: TvShowCreateInput): Promise<TvShow> {
    return await this.service.createTvShow({
      data: data,
      select: {
        createdAt: true,
        description: true,
        episodes: true,
        genres: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [TvShow] })
  @ApiNestedQuery(TvShowFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TvShow",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async tvShows(@common.Req() request: Request): Promise<TvShow[]> {
    const args = plainToClass(TvShowFindManyArgs, request.query);
    return this.service.tvShows({
      ...args,
      select: {
        createdAt: true,
        description: true,
        episodes: true,
        genres: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TvShow })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TvShow",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async tvShow(
    @common.Param() params: TvShowWhereUniqueInput
  ): Promise<TvShow | null> {
    const result = await this.service.tvShow({
      where: params,
      select: {
        createdAt: true,
        description: true,
        episodes: true,
        genres: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TvShow })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TvShow",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTvShow(
    @common.Param() params: TvShowWhereUniqueInput,
    @common.Body() data: TvShowUpdateInput
  ): Promise<TvShow | null> {
    try {
      return await this.service.updateTvShow({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          episodes: true,
          genres: true,
          id: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TvShow })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TvShow",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTvShow(
    @common.Param() params: TvShowWhereUniqueInput
  ): Promise<TvShow | null> {
    try {
      return await this.service.deleteTvShow({
        where: params,
        select: {
          createdAt: true,
          description: true,
          episodes: true,
          genres: true,
          id: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
